//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/google/uuid"
)

type Orders struct {
	ID          uuid.UUID `sql:"primary_key"`
	UserAddress string
	Value       float64
	TxHash      string
	BlockTime   time.Time
	CreatedAt   *time.Time
}
